### ISSUE TITLE
Purple textures when changing device

### ISSUE THREAD

**Issue by TheMaster6417** [UuuNyaa/blender_mmd_tools#15]
After loading a character into blender, the textures work fine. Once my scene was setup I sent it to my pc to render, only to find the textures are replaced with purple blank textures. Is this a bug or am I doing something wrong?

**Comment by listelin** [comment]
**In the imported state, the texture refers to the texture of the original PMX file.**

![texture location](https://user-images.githubusercontent.com/44924233/147721373-ab7acd98-1fb2-459e-9432-cc5984e43b1b.jpg)

Therefore, if only the blend file is projected on another PC, it will turn purple due to lack of texture.

**You can include this texture in the .blend file by checking File>External Data> Automatically Pack Resouces and saving it.**

![pack](https://user-images.githubusercontent.com/44924233/147721380-6d8ee50f-0f1d-46fb-8345-ac8031514ab4.jpg)
