### ISSUE TITLE
【IK Bug】Fix the difference between blender's IK pose and MMD's IK pose.

### ISSUE THREAD

**Issue by One-sixth** [UuuNyaa/blender_mmd_tools#47]
Hello.
I use some motion that rely heavily on IK constraints and poses.
I did some research and found a wrong setting in bone's mmd_ik_limit_override .

There is an example in the attachment. You can load it into mmd and blender and see the difference.
[ik_bug_check.zip](https://github.com/UuuNyaa/blender_mmd_tools/files/8837416/ik_bug_check.zip)

This is mmd's ik pose
![mmd_show](https://user-images.githubusercontent.com/23693633/171994436-f78def15-ab46-460b-a49e-825641df42ab.png)
This is the wrong blender ik pose. (Default)
![bad_blender_ik](https://user-images.githubusercontent.com/23693633/171994451-56ef4e3d-bdbf-4c03-b46d-668c8911f40e.png)
This is the correct blender ik pose.
![good_blender_ik](https://user-images.githubusercontent.com/23693633/171994463-e98eff5d-0abb-46a7-a6c4-d476329037a8.png)

We can put the fix function in the bone button, and just click it and repair automatically.
![change](https://user-images.githubusercontent.com/23693633/171994475-00762aa5-861d-4a3f-86cb-8362bf009707.png)

# Additional
The solution above is relatively simple. Works for most models.
If we need to cover some rare cases. We also need to move the IK Constraint Modifier to the Tip Bone, then turn off Use Tail. This allows models whose bones are not perfectly aligned to work correctly. But this will introduce more code changes.
E.g:
Move 右ひざ's IK Constraint Modifier to 右足首, then turn off Use Tail.
![close](https://user-images.githubusercontent.com/23693633/171995052-797d6d35-42a8-4179-96de-d64548eee7b9.png)

**Comment by nagadomi** [comment]
(I am not sure why Pose Space is used. Below is a very general answer and information related to this issue.)

MMD and Blender have different IK Solvers, so IK behavior is not fully compatible.
I think the model above has incompatible IK behavior due to the following two problems. Fixing it should solve the above problem.

1. foot bones are not straight
2. `足.(L|R)` bones have extra IK Limit settings (`Bone Properties > Inverse Kinematics > Limit X/Y/Z`)

`1.` causes incompatibility of bone rolls between MMD and Blender.
If a bone does not have a `Local Axes` setting, Blender will automatically calculate the bone roll for the bone (other than arm related bones). If the bone is not straight, the bone roll may be different from that of MMD internals. Bone roll affect the behavior of IK.

`2.` may not be compatible with all MMD motions/poses because they differ from typical MMD model IK settings.

**Comment by One-sixth** [comment]
> (I am not sure why Pose Space is used. Below is a very general answer and information related to this issue.)
> 
> MMD and Blender have different IK Solvers, so IK behavior is not fully compatible. I think the model above has incompatible IK behavior due to the following two problems. Fixing it should solve the above problem.
> 
> 1. foot bones are not straight
> 2. `足.(L|R)` bones have extra IK Limit settings (`Bone Properties > Inverse Kinematics > Limit X/Y/Z`)
> 
> `1.` causes incompatibility of bone rolls between MMD and Blender. If a bone does not have a `Local Axes` setting, Blender will automatically calculate the bone roll for the bone (other than arm related bones). If the bone is not straight, the bone roll may be different from that of MMD internals. Bone roll affect the behavior of IK.
> 
> `2.` may not be compatible with all MMD motions/poses because they differ from typical MMD model IK settings.

Thank you for the reply.
I think you can try it with other models as well. Maybe my bugfix version behaves more like MMD.

I've used this fix to render a video in Blender, and I've found that the fix works pretty well, almost identical to MMD, and stable, with no jittering that's different from MMD.

Although the blender IK cannot be exactly the same as MMD's IK. But apparently there are bug in the current implementation of mmd_tool that lead to larger IK errors.

MMD and Blender's IK behave very similarly, and I'm guessing that Blender uses CCD IK as well. Blender's IK solver does not support unit angles. This can lead to some difference in very tight constraints, but shouldn't make such a big error in such looser ones.

**Comment by UuuNyaa** [comment]
Thanks to you guys for your suggestions and discussion 😃 

I think the owner_space in mmd_ik_limit_override being `POSE` is purely a bug.
This is because a MMD bone angle limit should have a value relative to the bone.

- Adopt mmd_ik_limit_override: https://github.com/powroupi/blender_mmd_tools/issues/16
- Change ower_space: https://github.com/powroupi/blender_mmd_tools/commit/012592a5c18b0cc37a9eaf9a0dd6f3db8c0380a9#diff-c61de10ef2e8e90f66c7b0fb2e3317129bb50f23b4d0fca354f4f71bae31c4f6R370

So I intend ower_space to be `LOCAL`.
