### ISSUE TITLE
Non-Collision group mask seems to be broken in v2.4.0

### ISSUE THREAD

**Issue by Daniel8811** [UuuNyaa/blender_mmd_tools#54]
The masked groups of rigid bodies still interact with each other in v2.4.0 (Blender 3.1) unlike the behavior of MMD.
 
Related: https://github.com/UuuNyaa/blender_mmd_tools/issues/12#issuecomment-999085415

**Comment by UuuNyaa** [comment]
Thank you for the report 😃

The physics of Blender and MMD are calculated by completely different engines and cannot be the same.

However, some adjustments can be made.
Try adjusting **Non-Collision Distance Scale** to a larger value on **Adjust Last Operation**.
![image](https://user-images.githubusercontent.com/70152495/177042352-9e286190-fc31-4d75-8ab2-054cb09a6f65.png)

**Comment by Daniel8811** [comment]
Thanks for the reply!

I am trying it but i think i am still confused. 
 Could you explain, maybe in a few words, how does this `Non-Collision Distance Scale` work?
Is this applied to the collision group mask? What does the value mean?

**Comment by UuuNyaa** [comment]
> Could you explain, maybe in a few words, how does this Non-Collision Distance Scale work?
> What does the value mean?

The following decision formula is used to determine whether non-collision or not.
`Are rigid bodies non-collision? = distance < non_collision_distance_scale * (range1 + range2) / 2`
![Operators-Physics-Build-Rigid_Bodies](https://user-images.githubusercontent.com/70152495/177046554-1f74f540-4122-4e03-bf2d-99b5869dbe20.jpg)

In other words, larger `non_collision_distance_scale` is, the wider the range of non-collision to be determined.

> Will collision_group_number be ignored when this value is set?

No. Only different collision groups are affected.
Since an empty object must be created for each rigid body pair to be excluded in Blender, the number of empty objects should be reduced as much as possible depending on the condition.

**Comment by Daniel8811** [comment]
Thanks for the explanation! 

Just one more question. 
Will there be other bad impacts, apart from the performance reduction, if `Non-Collision Distance Scale` is set to a large value?

**Comment by UuuNyaa** [comment]
Depends on Blender's implementation, but probably nothing.
